export const FETCHING_ITEM_DATA = "FETCHING_ITEM_DATA"
export const FETCHING_ITEM_DATA_SUCCESS = "FETCHING_ITEM_DATA_SUCCESS"
export const FETCHING_ITEM_DATA_FAIL = "FETCHING_ITEM_DATA_FAIL"

export const ADD_ITEM_DATA = "ADD_ITEM_DATA"
export const ADD_ITEM_DATA_SUCCESS = "ADD_ITEM_DATA_SUCCESS"
export const ADD_ITEM_DATA_FAIL = "ADD_ITEM_DATA_FAIL"